name: Publish 
on:
  release:
    branches: [ public ]
jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - name: Fetch binaries
        run: |
          git clone --depth=1 --branch binaries https://github.com/${{ github.repository }}.git .
      - uses: softprops/action-gh-release@v3
        with:
          files: ./*.node
